default: &default
  oauth2:
    client_id: 56000117628-ueu939j1oqbm7fs2ng02tffach5tgqg4.apps.googleusercontent.com
    client_secret: 3pAXsB1Sr9SkIeOeK2HNzcS4
  cloud_storage:
    bucket: gs://pdadminsite-1351
    access_key_id: GOOGSTMTJRBZVNLR5SQE
    secret_access_key: JuQ99tEvmVkkX6Y5+f5JJhyp2wZ2K5eyJQvdfWx4

development:
  <<: *default

production:
  <<: *default
